import React from "react";

import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";

import AuthSession from "@/components/auth/AuthSession";
import StyledComponentsRegistry from "@/lib/AntdRegistry";

import SessionProvider from "../components/auth/SessionProvider";

import type { Metadata } from "next";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "아키플 스튜디오 2.0",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();
  return (
    <html>
      <Head>
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <StyledComponentsRegistry>
            <AuthSession>{children}</AuthSession>
          </StyledComponentsRegistry>
        </SessionProvider>
      </body>
    </html>
  );
}
