import "./globals.css";
import { Inter } from "next/font/google";
import AuthSession from "@/components/auth/AuthSession";
import type { Metadata } from "next";
import Nav from "@/components/nav/Nav";
import MainFooter from "@/components/MainFooter";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={inter.className}>
        <AuthSession>
          <Nav />
          {children}
          <MainFooter />
        </AuthSession>
      </body>
    </html>
  );
}
